### ISSUE TITLE
Updated Offsets as of 17th of Sept. 2016

### ISSUE THREAD

**Issue by aKalisch** [Wolf-88/aKalisch#1]
Here are the Offsets for my Hack.

`// Client.dylib Offsets
uint64_t localPlayerOffset = 0x514BAD8;
uint64_t playerOffset = 0x50C8658;
uint64_t glowInfoOffset = 0x595B3A0;

// Bind commands
uint64_t m_dwForceAttack = 0x505C5F0; // +attack
uint64_t m_dwForceAttack2 = 0x505C5FC; // +attack2
uint64_t m_dwForceJump = 0x59608B0; // +jump

// LocalPlayer & Entity Offsets
uint64_t teamOffset = 0x128;
uint64_t healthOffset = 0x134;
uint64_t flagOffset = 0x138;
uint64_t crosshairIDOffset = 0xB380;
uint64_t glowIndexOffset = 0xAC00;
uint64_t m_lifeState = 0x293;
uint64_t m_iDefaultFOV = 0x3B0C;
uint64_t m_iShotsFired = 0xABA0;
uint64_t m_vecOrigin = 0x16C;
uint64_t m_vecVelocity = 0x148;
uint64_t m_vecViewOffset = 0x13C;
uint64_t m_vecRotation = 0x3A68;
uint64_t m_iFlashAlpha = 0xABDC;
uint64_t m_bSpotted = 0xECD;
uint64_t m_bSpottedByMask = 0xF10;
uint64_t m_nHitboxSet = 0xFA8;
uint64_t m_dwBoneMatrix = 0x2C70; // m_nForceBone + 0xC2
uint64_t m_Local = 0x36F0;

// DT_Local Offsets
uint64_t m_viewPunchAngle = 0x68;
uint64_t m_aimPunchAngle = 0x74;
uint64_t m_aimPunchAngleVel = 0x80;

// DT_BaseWeapon Offsets
uint64_t DT_BaseWeapon = 0x5034910;
uint64_t m_iAmmo = 0x2D60;
uint64_t m_iAmmoRes = 0x2D64;
uint64_t m_hActiveWeapon = 0x2D6C;

// DT_BaseView Offsets
uint64_t DT_BaseView = 0x82B720;
uint64_t m_vecViewAngle = 0x8E20;

// Engine.dylib Offsets
uint64_t m_dwViewMatrix = 0x83B2D4;
uint64_t m_vecEngineOrigin = 0x8E81BC;
uint64_t m_vecEngineRotation = 0xAEB9A4;
// uint64_t m_vecEnginePointer = 0xEAE60C; No use at the moment
uint64_t m_iResolution = 0x596BAE0;

// Server.dylib Offsets
uint64_t m_numOfPlayers = 0xE2C78C;`

That are some more, because the hack now features Aimbot and other stuff. Just pick the ones you need.

I've took it offline because I don't want to risk to get "Untrusted".

**Comment by K2QGIT** [comment]
Thank you! Thats awesome!  and are all the structs for the aim bot in there? if so... Is it built into trigger or what is the initiating command?

**Comment by K2QGIT** [comment]
Also while testing, your wall works stronger and better than iseek, trigger seems to not be working?

**Comment by aKalisch** [comment]
Trigger is working fine.

I think you have the wrong Offset for CrossHairID is wrong. Missed that while updating.

Change `uint64_t crosshairIDOffset = 0xB380;` to `uint64_t crosshairIDOffset = 0xB390;`

**Comment by jananne** [comment]
@aKalisch, you should implement your hack into csgoGlow. I think everyone would be pleased. And when you don't want to use trigger or bunnyhop, just don't use it?

**Comment by Acornay** [comment]
MY CAPS ARE ALWAYS ON HELP!

**Comment by MyNameIsLebronJames** [comment]
what do I do with that whole thing? copy and paste it into Xcode?
